version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: ./src/docker/api/Dockerfile
    environment:
      USER_ID: $(id -u)
      GROUP_ID: $(id -g)
    volumes:
      - ./src/api:/usr/src/api
      - ./src/model:/usr/src/model
    ports:
      - 8000:8000

  web:
    build: ./src/web
    volumes:
      - ./src/web/src:/web/src
    ports:
      - 3000:3000

  local-ai:
    image: docker.uclv.cu/marcosmtr/whisper
    volumes:
      - ./models:/models
    ports:
      - 8080:8080